"""Stage 1: screen candidates, download PDBs + BindingDB slices, write HDF5 + checksum manifest + docs/DATA.md.

Offline-safe: if the network is unreachable the committed fixtures in tests/fixtures are used and
docs/DATA.md documents the manual download.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import h5py
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from qumolbind.data import bindingdb, pdb  # noqa: E402
from qumolbind.data.fixtures import FIXTURE_DIR, build_fixtures  # noqa: E402

CACHE = ROOT / "data_cache"
PROCESSED = CACHE / "processed"
# Candidate pool screened programmatically; selection = first accepted per distinct UniProt, max 3.
CANDIDATES = "3ERT 1UYD 1EVE 1CIL 2HYY 1STP 3PTB 1AZM".split()
MAX_TARGETS = 4  # 3ert, 1uyd, 1eve (main) + 1cil (zinc-site test fixture only; see DECISIONS D6/D16)


def sha256(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--max-targets", type=int, default=MAX_TARGETS)
    ap.add_argument("--skip-affinity", action="store_true", help="structures only (smoke does not need BindingDB)")
    args = ap.parse_args()
    PROCESSED.mkdir(parents=True, exist_ok=True)
    manifest: dict = {"created": datetime.now(timezone.utc).isoformat(), "files": {}, "targets": {}}
    offline = False
    try:
        cands = pdb.screen_many(CANDIDATES)
        pdb.save_screen(cands, CACHE / "screen.json")
    except Exception as e:
        print(f"[fetch_data] network unavailable: {e}")
        offline = True
        cands = []
    if cands and all(c.reasons and c.reasons[0].startswith("error:") for c in cands):
        offline = True
    selected = [c for c in cands if c.accepted][: args.max_targets]
    print("screen results:")
    for c in cands:
        print(f"  {c.pdb_id} res={c.resolution} lig={c.ligand_id} rotors={c.n_rotors} -> {'ACCEPT' if c.accepted else c.reasons}")

    if offline or not selected:
        print("[fetch_data] OFFLINE: using tests/fixtures only. See docs/DATA.md for manual download.")
        manifest["offline_fixture_only"] = True
    else:
        bindingdb_down = False
        for c in selected:
            tid = c.pdb_id.lower()
            pdb_path = pdb.download_pdb(c.pdb_id)
            fx = FIXTURE_DIR / "bindingdb_P00918_tiny.json" if c.uniprot[0] == "P00918" else None  # fixture = 1CIL's UniProt only
            aff = None
            if args.skip_affinity:
                print(f"  (affinity download skipped for {tid})")
            elif bindingdb_down and not (CACHE / f"bindingdb_{c.uniprot[0]}.json").exists():
                print(f"  !! affinity data skipped for {tid}: BindingDB judged unavailable earlier in this run")
            else:
                try:
                    aff = bindingdb.load_target(c.uniprot[0], CACHE, fixture=fx)
                except Exception as e:
                    print(f"  !! affinity data unavailable for {tid} ({c.uniprot[0]}): {e}")
                    bindingdb_down = True  # do not spend minutes of retries on every remaining target
                    aff = None
            h5 = PROCESSED / f"{tid}.h5"
            with h5py.File(h5, "w") as f:
                f.attrs.update(
                    pdb_id=c.pdb_id, ligand_id=c.ligand_id, ligand_chain=c.ligand_chain, ligand_resnum=c.ligand_resnum,
                    ligand_smiles=c.smiles, resolution=c.resolution, n_rotors=c.n_rotors, uniprot=c.uniprot[0],
                )
                if aff is not None:
                    g = f.create_group("affinity")
                    g.create_dataset("smiles", data=np.array(aff["smiles"], dtype="S"))
                    g.create_dataset("p_affinity", data=aff["p_affinity"].to_numpy(float))
                    g.create_dataset("measurement", data=np.array(aff["measurement"], dtype="S"))
                    g.create_dataset("n_measurements", data=aff["n_measurements"].to_numpy(int))
            manifest["files"][str(pdb_path.relative_to(ROOT))] = sha256(pdb_path)
            manifest["files"][str(h5.relative_to(ROOT))] = sha256(h5)
            manifest["targets"][tid] = {
                "pdb": c.pdb_id, "ligand": c.ligand_id, "smiles": c.smiles, "resolution": c.resolution,
                "n_rotors": c.n_rotors, "uniprot": c.uniprot[0], "n_affinity_ligands": 0 if aff is None else len(aff),
            }
            print(f"  wrote {h5.name}: {0 if aff is None else len(aff)} unique ligands")
        try:
            build_fixtures()
        except Exception as e:
            print(f"[fetch_data] fixture build skipped: {e}")

    (PROCESSED / "manifest.json").write_text(json.dumps(manifest, indent=2))
    write_docs(manifest, cands, offline)


def write_docs(manifest: dict, cands: list, offline: bool) -> None:
    L = ["# DATA", "", "Generated by `scripts/fetch_data.py` (do not edit by hand).", ""]
    L += ["## Sources", "",
          "- RCSB PDB: `https://files.rcsb.org/download/<ID>.pdb`; metadata `https://data.rcsb.org/rest/v1/core/entry/<ID>`;",
          "  ligand SMILES `https://data.rcsb.org/rest/v1/core/chemcomp/<CCD>`.",
          "- BindingDB (per-target, never the full dump): `https://www.bindingdb.org/rest/getLigandsByUniprots?uniprot=<ID>&cutoff=100000&response=application/json`.",
          "- ZINC-22 (stretch only, nothing downloaded): the file server `files.docking.org/zinc22/` returned HTTP 403 for anonymous access when checked; get a tranche (<= 50k molecules, .smi/.smi.gz) manually from CartBlanche22 (https://cartblanche22.docking.org) and load it with `qumolbind.data.zinc.load_tranche(<path>)`.", ""]
    L += ["## Candidate screen (resolution <= 2.5 A, one drug-like ligand, 3-8 RDKit rotatable bonds, non-covalent)", "",
          "| PDB | res (A) | ligand | heavy | rotors | verdict |", "|---|---|---|---|---|---|"]
    for c in cands:
        L.append(f"| {c.pdb_id} | {c.resolution} | {c.ligand_id} | {c.n_heavy} | {c.n_rotors} | {'ACCEPT' if c.accepted else '; '.join(c.reasons)} |")
    L += ["", "## Downloaded this run", ""]
    for k, v in manifest.get("files", {}).items():
        L.append(f"- `{k}` sha256 `{v[:16]}...`")
    L += ["", "## Selected targets", ""]
    for t, v in manifest.get("targets", {}).items():
        L.append(f"- **{t}**: ligand {v['ligand']} ({v['smiles']}), {v['n_rotors']} rotors, UniProt {v['uniprot']}, {v['n_affinity_ligands']} unique BindingDB ligands" + ("  (BindingDB request failed - re-run `make data`; no affinity model / ligand embedding for this target until then)" if v['n_affinity_ligands'] == 0 else ""))
    if offline:
        L += ["", "## OFFLINE", "", "Network was unreachable; only fixtures in `tests/fixtures/` are present.",
              "Manual download: fetch the PDB files from RCSB into `data_cache/pdb/` and BindingDB JSON into `data_cache/bindingdb_<UNIPROT>.json`, then re-run `scripts/fetch_data.py`."]
    L += ["", "## Fixtures", "", "`tests/fixtures/` holds, for offline tests: prepared pocket-truncated protein + native ligand for 1CIL and 3ERT, a pocket PDB of 1CIL, and a 60-record BindingDB slice for UniProt P00918 (1CIL only).", ""]
    (ROOT / "docs" / "DATA.md").write_text("\n".join(L))


if __name__ == "__main__":
    main()
